public class Conditions {
    
    public String lhs;
    public String rhs;
    public String condition;
    
    public String getLhs() {
        return lhs;
    }
    public void setLhs(String lhs) {
        this.lhs = lhs;
    }
    public String getRhs() {
        return rhs;
    }
    public void setRhs(String rhs) {
        this.rhs = rhs;
    }
    public String getCondition() {
        return condition;
    }
    public void setCondition(String condition) {
        this.condition = condition;
    }
}